version: '3.9'

services:
  loyalty-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loyalty-program-bot
    ports:
      - "8443:8080"
      - "5005:5005"
    env_file:
      - .env
    volumes:
      - loyalty_logs:/app  # Монтируем каталог логов

volumes:
  loyalty_logs: