version: '3.9'

services:
  loyalty-bot:
    build:
      context: .
      dockerfile: Dockerfile_LP
    container_name: loyalty-program-bot
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - .env
    volumes:
      - loyalty_logs:/app  # Монтируем каталог логов
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: loyalty-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
  loyalty_logs: